DROP DATABASE IF EXISTS db_vehicles;
CREATE DATABASE db_vehicles;
USE db_vehicles;
CREATE TABLE IF NOT EXISTS vehicles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    clientName VARCHAR(150) NOT NULL,
    brand VARCHAR(150) NOT NULL,
    plate VARCHAR(8) NOT NULL UNIQUE,
    combustion VARCHAR(50) NOT NULL,
    warranty TINYINT(1) NOT NULL DEFAULT 0,    
    cleanCar TINYINT(1) NOT NULL DEFAULT 0,
    oilChange TINYINT(1) NOT NULL DEFAULT 0,  
    brakeCheck TINYINT(1) NOT NULL DEFAULT 0,
    alignment TINYINT(1) NOT NULL DEFAULT 0,   
    image VARCHAR(500) DEFAULT NULL   
);