CREATE DATABASE IF NOT EXISTS vehiculos
USE vehiculos
CREATE TABLE IF NOT EXISTS vehiculo(
	id INT AUTO_INCREMENT PRIMARY KEY,
	clientName VARCHAR(150) NOT NULL,
    brand VARCHAR(150) NOT NULL,
    plate VARCHAR(8) NOT NULL UNIQUE,
    combustion VARCHAR(50) NOT NULL,
    warranty TINYINT NOT NULL,
    cleanCar TINYINT NOT NULL,
    tracking TINYINT NOT NULL,
    image VARCHAR(500) NOT NULL
);